const appName = 'Grocery Store';
export default {
    title_home: 'Home',
    title_dashboard: 'Dashboard',
    title_notifications: 'Notifications',
    next: 'Next',
    skip: 'Skip',
    start: 'Start',
    city_prompt: 'Choose a city',
    company_prompt: 'Choose a company',
    cafeteria_prompt: 'Choose a cafeteria',
    login_text: ' Please Login',
    login_text1: 'SignIn to Grocery App',
    login_text2: ' enter email & password to continue',
    forgot_text1: 'Reset Your Password',
    forgot_text2: 'you need One Time Password to reset password',
    signup_text: 'Sign Up',
    corporateRegister: 'Corporate Admin Register',
    signup_text1: 'Welcome to Grocery App',
    signup_text2: 'Let\'s get started',
    mobileHint: 'Registered Mobile Number / E-mail ID',
    uidExisting: 'Enter Mobile | E-Mail | EH-ID',
    uidNew: 'Mobile | E-Mail',
    passwordHint: 'Enter Password',
    confPasswordHint: 'Confirm Password',
    nameHint: 'Enter Name',
    emailHint: 'Enter Email',
    nameCorporateHint: 'Enter Corporate Name',
    mobileCorporateHint: 'Enter Corporate Phone',
    faxCorporateHint: 'Enter Corporate Fax',
    emailCorporateHint: 'Enter Corporate Email',
    webCorporateHint: 'Enter Corporate Website',
    documentCorporateHint: 'Select Corporate Verify Document',
    typeCorporateHint: 'Select Corporate Type',
    location: 'Enter Location',
    country: 'Select Country',
    states: 'Select State',
    city: 'Select City',
    pin: 'Select Pin Code',
    regNoHint: 'Enter Corporate GST/TIN/PAN',
    numberHint: '0123-456-789',
    signUp: 'Sign Up',
    signIn: 'Sign in',
    otpRequest: 'REQUEST OTP',
    sendOTP: 'SEND OTP',
    resetPassword: 'Reset Password',
    forgetPassword: 'Forgot Password ?',
    otpText: 'OTP Verification',
    otpSendText: 'We will send you One Time Password on this mobile number',
    otpSendMobile: `Enter OTP send to mobile`,
    enterMobile: 'Enter Mobile Number',
    generateOTP: 'Send OTP',
    notReceiveOTP: 'Didn’t receive the OTP ?',
    resendOTP: 'Resend OTP',
    verifyOTP: 'Verify OTP',
    id: 0,
    lang: 'English',
    langCode: 'en',
    appName: 'PushBase',
    signinTitle: 'Signin to Get Started!',
    email: 'Email',
    name: 'Name',
    password: 'Password',
    createPassword: 'Create New Password',
    confirmPassword: 'Confirm Password',
    createAcc: 'Create Account',
    forgot: 'Forgot Password',
    reset: 'Reset',
    logout: 'Logout',
    home: 'Home',
    categories: 'Categories',
    settings: 'Settings',

    // App intro sliders
    slide1Title: 'SAMPLE TITLE 1',
    slide1Text: 'This is sample description 1',
    slide2Title: 'SAMPLE TITLE 2',
    slide2Text: 'This is sample description 2',
    slide3Title: 'SAMPLE TITLE 3',
    slide3Text: 'This is sample description 3',

    //Validation messages
    required: 'is required',
    notValid: 'is not valid',
    tooShort: 'Minimum {count, number} chars required',
    doesntMatch: 'doesn\'t match',

    nameErrorMessage: 'Enter your correct name',
    mobileErrorMessage: 'Enter correct mobile number or email ID or EH ID',
    emailErrorMessage: 'Enter correct Email',
    regErrorMessage: 'Enter correct Document Number',
    webErrorMessage: 'Enter correct Website',
    faxErrorMessage: 'Enter correct Fax',
    passwordErrorMessage: 'Enter 8 character password',
    confirmPasswordErrorMessage: 'Password and confirm password must be same',
    successfullVerify: 'Successfully verified your Mobile Number',
    enterValidOTP: 'Please enter valid OTP send to your Mobile Number',
    passwordResetSuccess: 'Password successfully reset',
    searchHint: 'Search here...',
    addressHint: 'Enter Address',
    cityHint: 'Select City',
    zipHint: 'Select Zip Code',
    landMarkHint: 'Enter Landmark',
    stateHint: 'Select State',
    countryHint: 'Select Country',
    saveNext: 'SAVE & NEXT',
    save: 'SAVE',
    cancel: 'CANCEL',
    checkPinCode: 'Enter Delivery Pin Code',
    employeeAdd: 'Add New Employee',
    searchUser: 'Search By User Name...',
    doctorName: 'Enter Doctor Name',
    patientName: 'Enter Patient Name',
    dosageName: 'Enter Dosage Name',
    drugName: 'Enter Drugs Name',
    duration: 'Enter Duration',
    form: 'Enter Form',
    frequency: 'Enter Frequency',
    route: 'Enter Route',
    strength: 'Enter Strength',
    aadharNumber: 'Enter Aadhar Number',
    dob: 'Enter Date of Birth',
    gender: 'Enter Gender',
    height: 'Enter Height',
    weight: 'Enter Weight',
    profession: 'Enter Profession',
    salary: 'Enter Salary',
    relation: 'Enter Relation',
    bloodgroup: 'Enter Blood Group',
    diseases: 'Enter Existing Diseases',
    disability: 'Enter Disability',
    allergy: 'Enter Allergies',
    identification: 'Enter Identification Marks',
    answer: 'Write your answer',
    value: 'Enter Value',
    note: 'Type here.....',
    title: 'Enter Title',
};
